version: "3.8"

services:

  db:
    image: mysql:8.0
    container_name: movie_db

    ports:
      - "${DB_PORT_HOST}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: ${TZ}

    volumes:
      - ./database_qlphim/aireak_cinema_db.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${DATABASE_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - movie-net



  identity-service:

    build:
      context: .
      dockerfile: identity_service/Dockerfile

    container_name: identity_service

    ports:
      - "${IDENTITY_SERVICE_PORT}:8080"

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - movie-net



  movie-service:

    build:
      context: .
      dockerfile: movie_service/Dockerfile

    container_name: movie_service

    ports:
      - "${MOVIE_SERVICE_PORT}:8081"

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      TZ: ${TZ}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - movie-net



  ticket-service:

    build:
      context: .
      dockerfile: ticket_service/Dockerfile

    container_name: ticket_service

    ports:
      - "${TICKET_SERVICE_PORT}:8082"

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_ENVIRONMENT: ${PAYPAL_ENVIRONMENT}
      PAYPAL_FRONTEND_URL: ${PAYPAL_FRONTEND_URL}
      PAYPAL_VND_TO_USD_RATE: ${PAYPAL_VND_TO_USD_RATE}
      TZ: ${TZ}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - movie-net



  ai-service:

    build:
      context: .
      dockerfile: ai_service/Dockerfile

    container_name: ai_service

    ports:
      - "${AI_SERVICE_PORT}:8083"

    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      TMDB_API_KEY: ${TMDB_API_KEY}
      TZ: ${TZ}

    networks:
      - movie-net



  api-gateway:

    build:
      context: .
      dockerfile: api_gateway/Dockerfile

    container_name: api_gateway

    ports:
      - "${API_GATEWAY_PORT}:8888"

    environment:

      IDENTITY_SERVICE_HOST: ${IDENTITY_SERVICE_HOST}
      MOVIE_SERVICE_HOST: ${MOVIE_SERVICE_HOST}
      TICKET_SERVICE_HOST: ${TICKET_SERVICE_HOST}
      AI_SERVICE_HOST: ${AI_SERVICE_HOST}

      TZ: ${TZ}


    depends_on:
      - identity-service
      - movie-service
      - ticket-service
      - ai-service


    networks:
      - movie-net



  frontend:

    build:
      context: ./film_management_frontend
      dockerfile: Dockerfile

    container_name: film_management_frontend

    ports:
      - "${FRONTEND_PORT}:80"

    environment:
      TZ: ${TZ}

    depends_on:
      - api-gateway

    networks:
      - movie-net



networks:

  movie-net:
    driver: bridge



volumes:

  mysql_data: